learning_log/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    url('', include(('learning_logs.urls', 'learning_logs'), namespace='learning_logs')),
    url('users/', include(('users.urls', 'users'), namespace='users')),
]

learning_logs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),#wyszukiwanie pustego wyrazenia regularnego.Znak ^ to poczatek stringu, a $ koniec
    url(r'^topics/', views.topics, name='topics'),
    url(r'^topic/(?P<topic_id>\d)', views.topic, name='topic'),
    url(r'^content/(?P<entry_id>\d)', views.entry_content, name='entry_content'),
    url(r'^new_topic/', views.new_topic, name='new_topic'),
    url(r'^new_entry/(?P<topic_id>\d+)', views.new_entry, name='new_entry'),
    url(r'^edit_entry/(?P<entry_id>\d+)', views.edit_entry, name='edit_entry'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView

from . import views

urlpatterns = [
    url(r'^login/$', LoginView.as_view(template_name ='users/login.html'), name='login'), #korzystamy z budowanego w django widoku do logowania. Nalezy recznie podac link to szablonu z logowaniem
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
'''
Klasa Topic reprezentuje jeden artykul.
Klasa Topic dziedziczy po klasie models.Model.
models.Model oferuje podstawowa funkcjonalnosc modeli w Django

'''
class Topic(models.Model):
    text = models.CharField(max_length=50) #miejsce do wprowadzenia tekstu. Konieczne jest okreslenie maksylamej dlugosci
    date_added = models.DateTimeField(auto_now_add=True) # pole do przechowywania daty i godziny. Parametr auto_now_add automatycznie przypisuje artykulowi bierzaca godzine poczas tworzenia

    def __str__(self):
        return self.text
    
class Entry(models.Model):
    '''
    Klucz zewnetrzny to zapis z bazdy danych, oznaczajacy odwolanie do innego rekordu w bazie danych
    W omawianym przykladzie jest to polecenie laczace wpis z tematem
    Kazdemu utworzonemu tematowi zostal przypisany klucz (identyfikator)
    Kiedy Django tworzy polaczenia miedzy miedzy dwoma fragmentami danych, wowcza wykorzystuje klucze
    '''
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=200, default = "Title")
    text = models.TextField()#Pole do wpisywania teksu nieograniczone 
    date_added = models.DateTimeField(auto_now_add=True)
    
    
    '''
    Klasa Meta przechowywuje informacje dodatkowe przydatne podczas zarzadzania medelem
    '''
    class Meta:
        verbose_name_plural = 'entries'#Nazwa wyswietlana w panelu administratora
        
    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text',]
        labels = {'text': ''}
        
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['title', 'text']
        labels = {'text' : 'Text', 'title' : 'Title'}
        widgets = {'text' : forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render
from .models import Topic, Entry
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request, "learning_logs/index.html")

@login_required#Dekorator login_required sprawdza czy jestes zalogowany. jezeli nie przenosi uztkowniak do strony zdefiniowanej w ustawienaich
def topics(request):
    topics = Topic.objects.order_by('date_added')
    context = {'topics' : topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic' : topic, 'entries' : entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def entry_content(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    context = {'entry' : entry}
    return render(request, 'learning_logs/entry_content.html', context)

@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))#metoda reverse okresla adres URL na podstawie wskazanego wzorca
    context = {'form' : form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    topic=Topic.objects.get(id=topic_id)
    
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)#Tworzony jest nowy obiekt formularza, ale nie jest zapisywany do bazy danych
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    context = {'topic' : topic, 'form' : form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic=entry.topic
    if request.method != 'POST':
        form = EntryForm(instance=entry) #Tworzy obiekt formularza z danymi z oniektu entry
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    context = {'entry' : entry, 'topic' : topic, 'form' : form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user= form.save() #metoda save zwraca nowo utworzony obiekt
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form' : form}
    return render(request, 'users/register.html', context)

learning_logs/templates/base.html
<html>
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"><script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<title>Knowledge Base</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark navbar-static-top bg-dark">
  <a class="navbar-brand" href="{% url 'learning_logs:index' %}"><h4 class="display-4">Knowledge Base</h4></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
           <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
      </li>
   {% if user.is_authenticated %}
       <li class="nav-item"><span class="badge badge-light">Hello, {{ user.username }}</span></li>
       <li class="nav-item"><a class="nav-link" href="{% url 'users:logout' %}">Log Out</a></li>
   {% else %}
     <li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}">Login</a></li>
     <li class="nav-item"><a class="nav-link" href="{% url 'users:register' %}">Register</a></li>
   {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    <main role="main">
        {% block content  %}

        {% endblock  %}
    </main>

    <footer class="container">
      <p>Designed by Mateusz Glowinski</p>
    </footer>

</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "base.html" %}

{% block content  %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
<p>Entry edit:</p>
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
{% csrf_token %}
{{ form.as_p }}
<button name="submit">Save</button>
</form>
{% endblock  %}

learning_logs/templates/learning_logs/entry_content.html
{% extends 'base.html' %}

{% block content %}

  <p>Title: {{ entry.title }}</p>
  <p>{{ entry.text }}</p>
  <br><br>
  <p><a href="{% url 'learning_logs:edit_entry' entry.id %}"> Edit </a></p>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "base.html" %}

{% block content  %}
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Welcome!</h1>
          <p>This is a knowledgebase. You will fin here here valuable notes</p>
        </div>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
        </div>

        <hr>

      </div> 
{% endblock  %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "base.html" %}

{% block content  %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Add new entry</p>

<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
{% csrf_token %}
{{ form.as_p }}
<button name='submit'>Add Entry</button>
</form>
{% endblock  %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'base.html' %}

{% block content %}

  <p>Add new topic:</p>
  <form action="{% url 'learning_logs:new_topic' %}" method ='post'>
  {% csrf_token %} <!--CSRF protection--!>
  {{ form.as_p }} <!--Display form--!>
  <button name="submit">Add Topic</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'base.html' %}

{% block content %}

  <p>Topic: {{ topic }}</p>
  <p>Entries:</p>
  <ul>
  {% for entry in entries %}
    <li>
      <p><a href="{% url 'learning_logs:entry_content' entry.id %}">{{ entry.title }}</a></p>
    </li>
  {% empty %}
    <li>
      There are no entries for this topic yet.
    </li>
  {% endfor %}
  </ul>
<br><br>
<p><a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a></p>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "base.html" %}

{% block content  %}

<div = "container">
<h2>Topics</h2>
<div class="list-group">
    {% for topic in topics %}
        <a href="{% url 'learning_logs:topic' topic.id %}"> {{ topic }} </a>
    {% empty %}
        <li>No topics added</li>
    {% endfor %}
</div>
</div>
<a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>

{% endblock  %}

users/templates/users/login.html
{% extends "base.html" %}

{% block content %}

{% if form.errors %}
<p>User name and password are incorrect. Try again</p>
{% endif %}

<form method='post' action="{% url 'users:login' %}">
{% csrf_token %}
{{ form.as_p }}

<button name="submit">Login</button>
<input type="hidden" name="next" value="{% url 'learning_logs:index' %}" /><!--element next informuje o stronie na ktora zostaniemy przekierowani po udanym logowaniu--!>
</form>

{% endblock content %}

users/templates/users/register.html
{% extends "base.html" %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
        
    <button name="submit">register</button>
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>
    
{% endblock content %}